name: learn-github-actions
on:
  push:
    paths:
      - 'factorial.py'
jobs:
  hello-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "This is our first Github Workflow for specific filepath!"
