name: learn-github-actions
on:
  push:
    paths:
      - 'factorial.py'
jobs:
  hello-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "This is our first Github Workflow for specific filepath!"
      - name: Send message to ms teams
        uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
        with:
          webhook: 'https://gpsbulgaria.webhook.office.com/webhookb2/6545d14b-54d4-49a8-85fa-304cd49fe23c@663f645e-4d50-443f-8ff5-c38603b25744/IncomingWebhook/2be24e490a9a498c826558099503d19f/a7099d56-4218-423b-8c87-1f90e2b94122'
          message: "Someone change factorial.py"
