name: Parallel jobs
on: [push]
jobs:
  build-and-test job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this has been triggered ${{ github.event_name }} event"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Lint with pylint
        run: |
          python lint_test.py
      - name: Test
        run: |
          echo "Testing..."
      - run: echo "This job's status is ${{ job.status }}."
  build-and-test job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this has been triggered ${{ github.event_name }} event"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Lint with pylint
        run: |
          python lint_test.py
      - name: Test
        run: |
          echo "Testing..."
      - run: echo "This job's status is ${{ job.status }}." 
