name: Telerik-Github-Actions-Practice

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pycodestyle
    - name: Lint with pylint
      run: |
        python lint_test.py
    - name: Send message to ms teams
      uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
      with:
        webhook: 'https://gpsbulgaria.webhook.office.com/webhookb2/6545d14b-54d4-49a8-85fa-304cd49fe23c@663f645e-4d50-443f-8ff5-c38603b25744/IncomingWebhook/2be24e490a9a498c826558099503d19f/a7099d56-4218-423b-8c87-1f90e2b94122'
        message: "PyLint Status is OK!"
    - name: Style with pycodestyle
      run: |
        pycodestyle *.py
    - name: Unit testing
      run: |
        python3 -m doctest factorial.py
    - name: Build container
      run: echo "Building container iamge"
    - name: Deploy
      run: echo "Deploying to cluster"
